# Generated by Django 4.0.4 on 2022-04-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
