# Generated by Django 4.0.4 on 2022-04-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_rename_id_pokemon_pokemon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=0),
        ),
    ]
